apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: mern
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
    #port is the service port that will be exposed to other pods within the cluster.
    #targetPort is the port on which the backend container is listening.
      port: 5000 
      targetPort: 5000