version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: mern-db
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok" | mongosh localhost:27017/mernapp --quiet'
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: mern-backend
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    
     

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:5000/api
        container_name: mern-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  mongo-data:



