apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace }}
data:
  MONGO_HOST: {{ .Values.config.mongoHost | quote }}
  MONGO_PORT: {{ .Values.config.mongoPort | quote }}
  MONGO_DB: {{ .Values.config.mongoDb | quote }}
  PORT: {{ .Values.config.port | quote }}
  JWT_EXPIRES_IN: {{ .Values.config.jwtExpiresIn | quote }}
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  CORS_ORIGIN: {{ .Values.config.corsOrigin | quote }}
