apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: {{ .Values.namespace }}
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image }}
          ports:
            - containerPort: {{ .Values.mongodb.service.targetPort }}
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          resources:
{{ toYaml .Values.mongodb.resources | nindent 12 }}
          readinessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.runCommand('ping').ok"
                - --quiet
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 6
          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.runCommand('ping').ok"
                - --quiet
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc